import mysql from 'mysql2/promise';

/**
 * Test-only DB helper. Uses the same MariaDB the dev environment runs — tests
 * TRUNCATE all Phase-0 tables between runs so they are hermetic. Migrations are
 * applied once (idempotent).
 */

export async function resetDatabase(): Promise<void> {
  const conn = await mysql.createConnection({
    uri: process.env.DATABASE_URL ?? 'mysql://root:password@127.0.0.1:3306/horizon_trade',
  });
  try {
    await conn.query('SET FOREIGN_KEY_CHECKS=0');
    for (const t of [
      'round_trips',
      'fills',
      'order_intents',
      'positions',
      'cash_ledger',
      'activity_log',
      'token_stats',
      'trades',
      'bot_config',
      // Phase 1 immutable decision tables.
      'quantitative_decisions',
      'execution_cost_forecasts',
      'signal_candidates',
      'fee_tier_snapshots',
      // Phase 1.1 Gate 3B addition.
      'forecast_vs_realized_attributions',
      // Phase 1.1 Gate 3C additions — child tables first (FK order).
      'protection_events',
      'protection_instances',
      'protection_validation_runs',
      'protection_capabilities',
      'protection_policy_versions',
      // Phase 1.1 Gate 3D additions — child first.
      'shadow_certification_runs',
      'post_fill_revalidations',
      'shadow_execution_plans',
      // Phase 2F additions — child first (all FK to prior tables).
      'validation_incidents',
      'kelly_activation_evaluations',
      'rollback_records',
      'model_promotion_decisions',
      'promotion_evidence_bundles',
      'promotion_criteria',
      'challenger_evaluations',
      'challenger_versions',
      'claude_attribution_snapshots',
      'champion_challenger_outcome_comparisons',
      'observer_incremental_attribution',
      'unified_challenger_evidence',
      'unified_challenger_decisions',
      'statistical_audit_results',
      'statistical_reference_vectors',
      'statistical_audits',
      'deflated_sharpe_evaluations',
      'pbo_partition_results',
      'pbo_candidate_rankings',
      'pbo_evaluations',
      'validation_slice_failures',
      'validation_metric_slices',
      'validation_metrics',
      'cpcv_path_results',
      'cpcv_path_folds',
      'cpcv_paths',
      'cpcv_definitions',
      'validation_embargoes',
      'validation_fold_memberships',
      'validation_folds',
      'validation_split_policies',
      'experiment_candidate_versions',
      'experiment_parameters',
      'experiment_runs',
      'research_experiments',
      'dataset_integrity_checks',
      'dataset_exclusions',
      'dataset_memberships',
      'dataset_versions',
      'dataset_definitions',
      // Phase 2E additions — child first.
      'context_incidents',
      'champion_context_comparisons',
      'candidate_context_decisions',
      'context_ensemble_evidence',
      'product_context_snapshots',
      'global_context_snapshots',
      'macro_event_observations',
      'macro_event_definitions',
      'sector_memberships',
      'sector_definitions',
      'context_signal_values',
      'context_observations',
      'context_observer_runs',
      'context_policy_versions',
      'context_signal_definitions',
      'context_provider_health',
      'context_provider_definitions',
      // Phase 2D additions — child first.
      'champion_microstructure_comparisons',
      'microstructure_execution_decisions',
      'passive_fill_estimates',
      'market_impact_curves',
      'execution_cost_observer_snapshots',
      'trade_flow_windows',
      'microstructure_feature_values',
      'microstructure_feature_definitions',
      'order_book_levels',
      'order_book_snapshots',
      'order_book_gaps',
      'order_book_events',
      'order_book_sessions',
      'microstructure_shortlist_memberships',
      'microstructure_shortlist_runs',
      'microstructure_shortlist_policies',
      // Phase 2C additions — child first (all FK to prior tables).
      'champion_risk_comparisons',
      'stress_test_results',
      'stress_test_runs',
      'stress_scenario_definitions',
      'portfolio_drawdown_states',
      'weekly_loss_states',
      'daily_loss_states',
      'risk_cluster_memberships',
      'risk_clusters',
      'risk_cluster_snapshots',
      'correlation_pairs',
      'correlation_snapshots',
      'correlation_model_versions',
      'risk_limit_breaches',
      'candidate_risk_decisions',
      'position_risk_snapshots',
      'portfolio_risk_snapshots',
      'portfolio_risk_runs',
      'risk_limit_definitions',
      'risk_policy_versions',
      // Phase 2B additions — child first.
      'champion_challenger_routing_comparisons',
      'challenger_routing_decisions',
      'regime_transitions',
      'latent_state_mappings',
      'latent_state_assignments',
      'latent_state_model_versions',
      'change_point_events',
      'regime_evidence',
      'product_regime_snapshots',
      'global_regime_snapshots',
      'regime_observer_runs',
      'regime_transition_policies',
      'regime_definitions',
      // Phase 2A additions — child first.
      'research_observer_runs',
      'fingerprint_evidence',
      'fingerprint_snapshots',
      'fingerprint_definitions',
      'shortlist_decisions',
      'feature_values',
      'feature_calculation_runs',
      'feature_definitions',
      'product_quarantines',
      'product_hygiene_decisions',
      'product_metadata_observations',
      'universe_products',
      'universe_snapshots',
      // Phase 1.2-OPS additions — child first.
      'soak_preflight_runs',
      'adapter_selections',
      'soak_incidents',
      'soak_daily_reports',
      'soak_runs',
      // Phase 1.2 additions — child first.
      'shadow_daily_reports',
      'shadow_operation_runs',
      'forward_outcome_labels',
      'market_trade_observations',
      'ticker_observations',
      'candle_observations',
      'product_market_states',
      'market_data_gaps',
      'market_data_events',
      'market_stream_subscriptions',
      'market_stream_sessions',
      // Phase 1.1.b additions.
      'execution_fences',
      'reconciliation_runs',
      'reconciliation_actions',
      // Phase 1.1 Gate 2 additions.
      'lineage_events',
      'outcome_labels',
      'strategy_routing_decisions',
      'setup_evaluations',
      'eligibility_decisions',
      'market_observations',
      'decision_chains',
      'scan_runs',
    ]) {
      await conn.query(`TRUNCATE TABLE \`${t}\``);
    }
    await conn.query('SET FOREIGN_KEY_CHECKS=1');
  } finally {
    await conn.end();
  }
}
