import { createHash } from 'node:crypto';
import type {
  IntrospectedCheckConstraint,
  IntrospectedColumn,
  IntrospectedIndex,
  IntrospectedSchema,
  IntrospectedTable,
} from './mariadb-introspect';

/**
 * Convert an introspected MariaDB schema into a drizzle-kit v0.31.10
 * snapshot object (Phase 1.1 Gate 1 §Option 1).
 *
 * The output matches the layout drizzle-kit itself would produce for a
 * mysql project — verified against a reference snapshot generated by
 * `drizzle-kit generate` on a controlled schema. See
 * `PHASE1_gate1.md § snapshot format` for the exact fields and their
 * MariaDB source mapping.
 *
 * NON-DRIZZLE-REPRESENTABLE DETAILS
 * Drizzle-kit's snapshot format does NOT record:
 *   - `json_valid(<col>)` check constraints auto-generated by MariaDB on
 *     `json`-typed columns
 *   - Generated-column expressions on non-`generated()` schema declarations
 *   - MariaDB's `int(11)` display width (drizzle stores canonical `int`)
 * We preserve those separately in `schema-fingerprint.ts` so no
 * MariaDB-only structural information is silently discarded.
 */

export interface DrizzleSnapshot {
  version: '5';
  dialect: 'mysql';
  id: string;
  prevId: string;
  tables: Record<string, DrizzleSnapshotTable>;
  views: Record<string, never>;
  _meta: {
    schemas: Record<string, never>;
    tables: Record<string, never>;
    columns: Record<string, never>;
  };
  internal: {
    tables: Record<string, never>;
    indexes: Record<string, never>;
  };
}

export interface DrizzleSnapshotTable {
  name: string;
  columns: Record<string, DrizzleSnapshotColumn>;
  indexes: Record<string, DrizzleSnapshotIndex>;
  foreignKeys: Record<string, DrizzleSnapshotForeignKey>;
  compositePrimaryKeys: Record<string, DrizzleSnapshotCompositePK>;
  uniqueConstraints: Record<string, DrizzleSnapshotUniqueConstraint>;
  checkConstraint: Record<string, never>;
}

export interface DrizzleSnapshotColumn {
  name: string;
  type: string;
  primaryKey: boolean;
  notNull: boolean;
  autoincrement: boolean;
  default?: string | number | boolean;
  onUpdate?: true;
  generated?: { as: string; type: 'stored' | 'virtual' };
}

export interface DrizzleSnapshotIndex {
  name: string;
  columns: string[];
  isUnique: boolean;
}

export interface DrizzleSnapshotForeignKey {
  name: string;
  tableFrom: string;
  columnsFrom: string[];
  tableTo: string;
  columnsTo: string[];
  onUpdate: string;
  onDelete: string;
}

export interface DrizzleSnapshotCompositePK {
  name: string;
  columns: string[];
}

export interface DrizzleSnapshotUniqueConstraint {
  name: string;
  columns: string[];
}

// ---------------------------------------------------------------------------
// Type normalisation — MariaDB display type → drizzle canonical type
// ---------------------------------------------------------------------------

/**
 * MariaDB's `information_schema.COLUMNS.COLUMN_TYPE` renders integers with a
 * display width (e.g. `int(11)`, `tinyint(1)`), which drizzle's schema model
 * ignores. We collapse:
 *
 *   int(11)      → int
 *   bigint(20)   → bigint
 *   smallint(6)  → smallint
 *   tinyint(1)   → boolean       (drizzle's boolean maps to TINYINT(1))
 *   tinyint(4)   → tinyint
 *   varchar(N)   → varchar(N)    (width IS significant)
 *   decimal(P,S) → decimal(P,S)
 *   enum(...)    → enum(...)     (verbatim including quoted values)
 *   text/mediumtext/longtext → text
 *   timestamp/datetime           → verbatim
 *   json         → json
 */
export function normalizeColumnType(
  columnType: string,
  columnName: string,
  checkConstraints: IntrospectedCheckConstraint[],
): string {
  const lower = columnType.toLowerCase().trim();
  // TINYINT(1) is drizzle's boolean.
  if (lower === 'tinyint(1)') return 'boolean';
  // Integer widths — strip them.
  const intMatch = lower.match(/^(tinyint|smallint|mediumint|int|bigint)\(\d+\)( unsigned)?$/);
  if (intMatch) return intMatch[1] + (intMatch[2] ?? '');
  // MariaDB stores json columns as longtext with a `json_valid(<col>)` check
  // constraint. Drizzle stores them as `json`. If we see a longtext column
  // whose check constraint mentions json_valid on this column, treat it as
  // json (matches what drizzle-kit generate would write from a schema.ts
  // `json('col')` declaration).
  if (lower === 'longtext') {
    const jsonValidRe = new RegExp(`json_valid\\(\`?${columnName}\`?\\)`, 'i');
    if (checkConstraints.some((c) => jsonValidRe.test(c.clause))) return 'json';
  }
  // Everything else — return verbatim (case preserved for readability of enum values).
  return columnType;
}

// ---------------------------------------------------------------------------
// Default normalisation
// ---------------------------------------------------------------------------

/**
 * MariaDB reports defaults with quirks:
 *   - `CURRENT_TIMESTAMP()` → drizzle stores `"(now())"`
 *   - `'0'` (string) → drizzle stores `"'0'"` (SQL-quoted)
 *   - Numeric literals like `0` → drizzle stores `0` (unquoted)
 *   - Boolean-mapped tinyint(1) default `1`/`0` → drizzle stores `true`/`false`
 *   - `NULL` → drizzle omits the `default` field entirely
 *   - Generated-column virtual `NULL` default → omit
 */
export function normalizeDefault(
  columnDefault: string | null,
  dataType: string,
  isBoolean: boolean,
): DrizzleSnapshotColumn['default'] | undefined {
  if (columnDefault === null) return undefined;
  const raw = columnDefault.trim();
  if (raw.toUpperCase() === 'NULL') return undefined;

  // Timestamps: current_timestamp() family → drizzle's "(now())".
  if (/^(current_timestamp|current_timestamp\(\)|now\(\))$/i.test(raw)) {
    return '(now())';
  }

  // Boolean columns: '1'/'0' or true/false → drizzle boolean literal.
  if (isBoolean) {
    if (raw === '1' || raw.toLowerCase() === 'true') return true;
    if (raw === '0' || raw.toLowerCase() === 'false') return false;
  }

  // Numeric defaults on numeric columns: keep as JS number.
  const numericTypes = new Set(['int', 'bigint', 'tinyint', 'smallint', 'mediumint', 'decimal']);
  if (numericTypes.has(dataType.toLowerCase())) {
    // MariaDB double-quotes decimal defaults sometimes ("'0'"); strip.
    const unquoted = raw.replace(/^'|'$/g, '');
    if (/^-?\d+(\.\d+)?$/.test(unquoted)) {
      if (dataType.toLowerCase() === 'decimal') {
        // Drizzle stores decimal defaults as SQL-quoted strings ("'0'"), not
        // numbers. MariaDB pads to the column scale ('0.00' on DECIMAL(5,2));
        // canonicalize back to the minimal representation so we match what a
        // schema.ts `.default('0')` produces.
        return `'${canonicalizeDecimalString(unquoted)}'`;
      }
      const n = Number(unquoted);
      if (Number.isFinite(n)) return n;
    }
  }

  // ENUM defaults come back as 'value' — keep the quotes.
  if (dataType.toLowerCase() === 'enum') {
    // Already single-quoted usually; strip and re-quote for consistency.
    const unquoted = raw.replace(/^'|'$/g, '');
    return `'${unquoted}'`;
  }

  // String defaults: preserve the SQL quoting drizzle expects.
  if (/^'.*'$/.test(raw)) return raw;
  return `'${raw}'`;
}

/**
 * Strip trailing zeros in the fractional part of a decimal literal.
 *   '0.00'  → '0'
 *   '0.50'  → '0.5'
 *   '1.230' → '1.23'
 *   '2'     → '2'
 * Preserves the sign and any leading digits.
 */
function canonicalizeDecimalString(s: string): string {
  if (!/^-?\d+(\.\d+)?$/.test(s)) return s;
  if (!s.includes('.')) return s;
  return s.replace(/(\.\d*?)0+$/, '$1').replace(/\.$/, '');
}

// ---------------------------------------------------------------------------
// Column conversion
// ---------------------------------------------------------------------------

function toSnapshotColumn(
  col: IntrospectedColumn,
  checkConstraints: IntrospectedCheckConstraint[],
): DrizzleSnapshotColumn {
  const type = normalizeColumnType(col.columnType, col.name, checkConstraints);
  const isBoolean = type === 'boolean';
  const isAutoIncrement = /auto_increment/i.test(col.extra);
  const notNull = !col.isNullable;
  // Drizzle v5 snapshots always set primaryKey: false on the column
  // itself; PK info lives in compositePrimaryKeys.
  const out: DrizzleSnapshotColumn = {
    name: col.name,
    type,
    primaryKey: false,
    notNull,
    autoincrement: isAutoIncrement,
  };
  const dflt = normalizeDefault(col.columnDefault, col.dataType, isBoolean);
  if (dflt !== undefined) out.default = dflt;
  if (/on update/i.test(col.extra)) out.onUpdate = true;
  if (col.isGenerated && col.generationExpression) {
    // MariaDB returns the expression WITHOUT outer parens; drizzle-kit
    // wraps them. Add them here so drizzle-kit generate sees byte-equal
    // strings and produces no diff.
    const expr = col.generationExpression.trim();
    const wrapped = expr.startsWith('(') && expr.endsWith(')') ? expr : `(${expr})`;
    out.generated = {
      as: wrapped,
      type: col.isVirtual ? 'virtual' : 'stored',
    };
    // Generated columns don't have a normal default; drop it if we set one.
    delete out.default;
  }
  return out;
}

// ---------------------------------------------------------------------------
// Index/unique routing
// ---------------------------------------------------------------------------

/**
 * Drizzle's snapshot has TWO homes for uniqueness:
 *   - `indexes[N]` with `isUnique: true` — from `uniqueIndex('name').on(...)`
 *   - `uniqueConstraints[N]` — from `.unique()` on a column
 *
 * MariaDB doesn't distinguish these at the information_schema level.
 * We use the drizzle-orm naming convention: `.unique()` on column `X` in
 * table `Y` produces a UNIQUE KEY named `Y_X_unique`. Any UNIQUE key
 * matching that pattern goes to `uniqueConstraints`; everything else
 * (including single-column UNIQUE indexes with an explicit name) goes to
 * `indexes` with `isUnique: true`.
 *
 * This heuristic is imperfect — a schema author could name a
 * `uniqueIndex` `foo_bar_unique` and it would be routed as a
 * uniqueConstraint. Snapshot-vs-schema.ts diff detection catches such
 * mismatches; the caller should rename the offending index or add an
 * override map.
 */
function isColumnLevelUnique(tableName: string, idx: IntrospectedIndex): boolean {
  if (!idx.isUnique) return false;
  if (idx.columns.length !== 1) return false;
  const col = idx.columns[0];
  return idx.name === `${tableName}_${col}_unique`;
}

// ---------------------------------------------------------------------------
// Table conversion
// ---------------------------------------------------------------------------

function toSnapshotTable(t: IntrospectedTable): DrizzleSnapshotTable {
  // Primary key columns from PRIMARY index.
  const pkIdx = t.indexes.find((i) => i.isPrimary);
  const pkColumns = pkIdx ? pkIdx.columns : [];

  // Columns.
  const columns: Record<string, DrizzleSnapshotColumn> = {};
  for (const col of t.columns) {
    columns[col.name] = toSnapshotColumn(col, t.checkConstraints);
  }

  // Composite PKs — drizzle stores PK under compositePrimaryKeys even for
  // single-column PKs, with a synthetic name `<table>_<col>` (matches how
  // drizzle-kit generate writes it).
  const compositePrimaryKeys: Record<string, DrizzleSnapshotCompositePK> = {};
  if (pkColumns.length > 0) {
    const pkName = `${t.name}_${pkColumns.join('_')}`;
    compositePrimaryKeys[pkName] = { name: pkName, columns: [...pkColumns] };
  }

  // Indexes & uniqueConstraints. MariaDB automatically creates a
  // supporting index for every foreign-key column set; drizzle-kit's
  // snapshot does NOT record those, so we skip any index whose name
  // exactly matches a foreign-key constraint on this table.
  const fkNames = new Set(t.foreignKeys.map((fk) => fk.name));
  const indexes: Record<string, DrizzleSnapshotIndex> = {};
  const uniqueConstraints: Record<string, DrizzleSnapshotUniqueConstraint> = {};
  for (const idx of t.indexes) {
    if (idx.isPrimary) continue;
    if (fkNames.has(idx.name)) continue; // FK auto-index
    if (isColumnLevelUnique(t.name, idx)) {
      uniqueConstraints[idx.name] = { name: idx.name, columns: [...idx.columns] };
    } else {
      indexes[idx.name] = {
        name: idx.name,
        columns: [...idx.columns],
        isUnique: idx.isUnique,
      };
    }
  }

  // Foreign keys.
  const foreignKeys: Record<string, DrizzleSnapshotForeignKey> = {};
  for (const fk of t.foreignKeys) {
    foreignKeys[fk.name] = {
      name: fk.name,
      tableFrom: t.name,
      columnsFrom: [...fk.columns],
      tableTo: fk.referencedTable,
      columnsTo: [...fk.referencedColumns],
      onUpdate: normaliseFkAction(fk.onUpdate),
      onDelete: normaliseFkAction(fk.onDelete),
    };
  }

  return {
    name: t.name,
    columns,
    indexes,
    foreignKeys,
    compositePrimaryKeys,
    uniqueConstraints,
    checkConstraint: {},
  };
}

function normaliseFkAction(v: string): string {
  const s = v.toLowerCase().trim();
  if (s === 'no action') return 'no action';
  if (s === 'restrict') return 'restrict';
  if (s === 'cascade') return 'cascade';
  if (s === 'set null') return 'set null';
  if (s === 'set default') return 'set default';
  return s;
}

// ---------------------------------------------------------------------------
// Snapshot id chain — deterministic, derived from tag names
// ---------------------------------------------------------------------------

/**
 * Deterministic UUIDv5-like identifier from a tag. Not RFC-4122 v5 exactly
 * (uses MD5 rather than SHA-1 and skips the namespace) but stable and
 * unique across our migration tags.
 */
export function deterministicSnapshotId(tag: string): string {
  if (tag === '') return '00000000-0000-0000-0000-000000000000';
  const h = createHash('md5').update(`horizon-drizzle-snapshot:${tag}`).digest('hex');
  return `${h.slice(0, 8)}-${h.slice(8, 12)}-${h.slice(12, 16)}-${h.slice(16, 20)}-${h.slice(20, 32)}`;
}

// ---------------------------------------------------------------------------
// Top-level snapshot assembly
// ---------------------------------------------------------------------------

export function buildDrizzleSnapshot(
  schema: IntrospectedSchema,
  currentTag: string,
  previousTag: string,
): DrizzleSnapshot {
  const tables: Record<string, DrizzleSnapshotTable> = {};
  for (const t of schema.tables) {
    tables[t.name] = toSnapshotTable(t);
  }
  return {
    version: '5',
    dialect: 'mysql',
    id: deterministicSnapshotId(currentTag),
    prevId: deterministicSnapshotId(previousTag),
    tables,
    views: {},
    _meta: { schemas: {}, tables: {}, columns: {} },
    internal: { tables: {}, indexes: {} },
  };
}
